apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  antlia-web-frontity-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: www.antlia-web-frontity.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  antlia-web-frontity
                port:
                  number: 3000
          # - path: /v2
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: web2
          #       port:
          #         number: 8070