{{- $fullName := include "nodeapp-charts.fullname" . -}}
{{- $port := .Values.service.port -}}
#apiVersion: networking.k8s.io/v1beta1
apiVersion: networking.k8s.io/v1
#apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "nodeapp-charts.fullname" . }}
  labels:
    {{- include "nodeapp-charts.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ .path }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $port }}
  {{- end }}
