// types contains the constants for the app


export const userConstants = {
  SIGN_UP_LOADING: 'SIGN_UP_LOADING',
  SIGN_UP_ERROR: 'SIGN_UP_ERROR',

  GET_ERRORS: 'GET_ERRORS',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  USER_DATA_RES: 'USER_DATA_RES',
  IS_LOADING: 'IS_LOADING',

  CONTACT_SUBMIT_LOADING:'CONTACT_SUBMIT_LOADING',
  REQUEST_DEMO_LOADING:'REQUEST_DEMO_LOADING',
  COURSE_REGISTER_LOADING:'COURSE_REGISTER_LOADING',

  INVEST_SUBMIT_LOADING:'INVEST_SUBMIT_LOADING',
  
  REGISTERATION_FORM: "REGISTERATION_FORM",

  APPLICATION_FORM_DATA: 'APPLICATION_FORM_DATA',
  TOGGLE_MODAL:'TOGGLE_MODAL'
};
export const LOCALE_SET = 'LOCALE_SET';