apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nodeapp-charts.fullname" . }}
  labels:
    {{- include "nodeapp-charts.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nodeapp-charts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nodeapp-charts.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagenetworking.k8s.io/v1PullPolicy: {{ .Values.image.imagepullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

