apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-antia-charts.fullname" . }}
  labels:
    {{- include "helm-antia-charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
# spec:
#   type: {{ .Values.service.type }}
#   ports:
#     - port: {{ .Values.service.port }}
#       targetPort: http
#       protocol: TCP
#       name: http
#   selector:
    {{- include "helm-antia-charts.selectorLabels" . | nindent 4 }}
